### ISSUE TITLE
Review Session and rewards calculation technical design

### ISSUE THREAD

**Issue by prasadpilla** [coronagoapp/solocoin-backend#33]
there are couple of edge cases for session tracking, for example you won't be able to send update to backend if the user uninstalls the app after the "home" session is started. Need to think about this, but let's focus on the integration for now.

Also think of any other edge cases or problems in the design and suggest solutions or re-design.

**Comment by arunava59** [comment]
The user does not even need to uninstall, he can simply activate the home-session and switch off the internet and that would do.
I think to counter such cases we need some sort of persistent connection that can notify us at the backend whenever the user disconnects from our app, like sockets.

**Comment by prasadpilla** [comment]
@arunava59 yeah i was thinking in those lines, not necessarily a persistent connection, hear beat kind of polling could probably work.

For example they could send a message to backend every 5 mins when they run the geofencing logic, saying "I am still home/away", then on the server, if we don't receive the message for two intervals we can end the current session.

**Comment by arunava59** [comment]
Yes, that is indeed possible.
So I am thinking like this - We can keep a map `{user => last_heartbeat_time}`, and once a session starts, after every fixed interval the mobile app shall hit the api to update this `heart_beat` time for the user.
And in the backend we would have a recursive background worker which would periodically go through all the active sessions at the moment, compare their user's heartbeat time with the current time, and end the session if necessary.
And since we will have a lot of hits on this map, maybe Redis would fit good for this purpose.
Thoughts ??

**Comment by prasadpilla** [comment]
@arunava59  I was thinking we can probably have frontend call the same API i.e sessions/create every five minutes and we can handle the logic of termination at backend. 

and last_heart_beat_time should can be stored in session table probably for now and redis later when we hit scale.

**Comment by arunava59** [comment]
@prasadpilla Yes that can be done, however we might lose the actual session duration of the user ? Like say in v2 we would probably be asked to display all the session durations as a list for an user (and not just the total_duration), how would we handle it ?

**Comment by prasadpilla** [comment]
@arunava59 yeah didn't mean to say we end the session altogether on every heartbeat, but change logic such that we don't create new sessions if the last session is of same time. But yeah that could get complicated. I saw you and @nronas have discussed about this in chat, i'll read through it and add if i have any inputs. You guys go ahead with the approach you discussed
